contest_name: ARRL 10-Meter Contest
contest_code: ARRL-10
CALLSIGN
LOCATION
CATEGORY-ASSISTED
CATEGORY-BAND
CATEGORY-MODE
CATEGORY-POWER
CATEGORY-STATION
CATEGORY-TRANSMITTER
CATEGORY-OVERLAY
CLUB
NAME
ADDRESS
ADDRESS-CITY
ADDRESS-STATE-PROVINCE
ADDRESS-POSTALCODE
ADDRESS-COUNTRY
EMAIL