contest_name: November Sweepstakes CW
contest_code: ARRL-SS-CW
LOCATION
CALLSIGN
CATEGORY-ASSISTED
CATEGORY-BAND
CATEGORY-MODE
CATEGORY-POWER
CATEGORY-OPERATOR
CLUB
NAME
ADDRESS
ADDRESS-CITY
ADDRESS-STATE-PROVINCE
ADDRESS-POSTALCODE
ADDRESS-COUNTRY
EMAIL